version: 0.1
phases:
  install:
    commands:
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - myApp.zip
  # files:
  #   - package.json
  #   - appspec.yaml
  #   - scripts/**/*
  #   - public/**/*
