version: 0.1
phases:
  install:
    commands:
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - package.json
    - appspec.yml
    - buildspec.yml
    - Dockerfile
    - Dockerrun.aws.json
    - scripts/**/*
    - public/**/*
